REVOKE ALL ON SCHEMA PUBLIC FROM PUBLIC;

CREATE DATABASE kapselistudio;
\c kapselistudio

REVOKE ALL ON SCHEMA PUBLIC FROM PUBLIC;

CREATE USER app LOGIN PASSWORD 'app';
GRANT ALL PRIVILEGES ON DATABASE kapselistudio TO app;
GRANT ALL PRIVILEGES ON SCHEMA public TO app;
