---
# Prerequisites: an Ubuntu 20.04 VPS with a root user that has
# ~/.ssh/id_rsa.pub in authorized_keys

- name: Setup Kapselistudio VPS
  hosts: all
  become: true
  roles:
    - dokku_bot.ansible_dokku
    - geerlingguy.security

  vars_files:
    - vars/security.yml

  vars:
    dokku_plugins:
      - name: postgres
        url: https://github.com/dokku/dokku-postgres.git
      - name: letsencrypt
        url: https://github.com/dokku/dokku-letsencrypt.git

  pre_tasks:
    - name: Update apt
      apt:
        update_cache: true
        cache_valid_time: 3600
        force_apt_get: true

  tasks:
    - name: add OpenSSH to ufw
      ufw:
        rule: allow
        name: OpenSSH

    - name: add HTTP to ufw
      ufw:
        rule: allow
        port: "80"

    - name: add HTTPS to ufw
      ufw:
        rule: allow
        port: "443"

    - name: enable ufw
      ufw:
        state: enabled

    - name: create episodes directory
      ansible.builtin.file:
        path: /home/dokku/kapselistudio_episodes
        state: directory
        mode: "0755"

    - name: dokku apps:create kapselistudio
      dokku_app:
        app: &kapselistudio kapselistudio

    - name: postgres:create kapselistudio
      environment:
        POSTGRES_IMAGE: postgres
        POSTGRES_IMAGE_VERSION: 14.4
      dokku_service_create:
        name: *kapselistudio
        service: postgres

    - name: postgres:link kapselistudio kapselistudio
      dokku_service_link:
        app: *kapselistudio
        name: *kapselistudio
        service: postgres

    - name: dokku config
      dokku_config:
        app: *kapselistudio
        config:
          MIX_ENV: prod
          SECRET_KEY_BASE: "{{ secret_key_base }}"
          DOKKU_LETSENCRYPT_EMAIL: me@rarelyneeded.com
          PORT: "5000"
          EPISODE_DIR: "/kapselistudio_episodes"

    # Not sure why this "dokku.me" global domain is added by default, but it needs to go
    - name: dokku disable global domain
      dokku_domains:
        app: *kapselistudio
        global: true
        state: clear
        domains:
          - dokku.me

    - name: dokku domain
      dokku_domains:
        app: *kapselistudio
        domains:
          - kapselistudio.net

    - name: dokku storage
      dokku_storage:
        app: *kapselistudio
        mounts:
          - /home/dokku/kapselistudio_episodes:/kapselistudio_episodes
        create_host_dir: true

    # TODO: There probably is a better way to add my key to dokku's authorized_keys...
    - name: create .ssh dir for dokku
      file:
        path: "/home/dokku/.ssh"
        state: directory

    - name: create empty authorized_keys file
      file:
        path: "/home/dokku/.ssh/authorized_keys"
        state: touch

    - name: add public key to authorized_keys
      lineinfile:
        path: "/home/dokku/.ssh/authorized_keys"
        line: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    - name: install psql client
      ansible.builtin.apt:
        name: postgresql-client

    # TODO: Document how to set up the wildcard Letsencrypt certificate
